
#Все настройки, связанные с основным игровым процессом
[gameplay]
	#minecolonies.config.enablecitizenvoices.comment [По умолчанию: true]
	enablecitizenvoices = true
	#По умолчанию, при размещении схемы возле других зданий, уже существующие здания будут показаны как если бы они были 5 уровня, и с синим контуром вокруг. Это можно отключить, установив для него значение false. [По умолчанию: true]
	neighborbuildingrendering = true
	#How close a building needs to be to another to be considered a neighbor, in blocks. -1 = intersecting, 0 = touching [По умолчанию: 4, мин: -2, макс: 16]
	#Range: -2 ~ 16
	neighborbuildingrange = 4
	#How close (in blocks) you need to be to see work orders while wearing the Build Goggles. [По умолчанию: 50, мин: 1, макс: 250]
	#Range: 1 ~ 250
	buildgogglerange = 50
	#При значении true границы колонии, отображаемые при использовании инструмента строительства, будут окрашены в цвет команды колонии. При значении false колония, в которой вы находитесь, будет белой, а любая другая колония — красной. [По умолчанию: true]
	colonyteamborders = true

